info:
  version: @pom.version@
  stage: test

logging:
  file: target/boot-admin-sample.log

spring:
  application:
    name: @pom.artifactId@
  jackson:
    serialization:
     indent-output: true

endpoints:
  health:
    sensitive: false
  cors:
    allowed-headers: '*'
    allowed-origins: '*'
    allowed-methods: '*'